const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.EightDir,
		C3.Behaviors.scrollto,
		C3.Behaviors.bound,
		C3.Behaviors.LOS,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Behaviors.Timer,
		C3.Behaviors.Pathfinding,
		C3.Plugins.Mouse,
		C3.Behaviors.solid,
		C3.Behaviors.shadowcaster,
		C3.Plugins.shadowlight,
		C3.Plugins.Text,
		C3.Plugins.Touch,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.System.Exps.random,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Behaviors.Pathfinding.Acts.Stop,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Cnds.Every,
		C3.Behaviors.Pathfinding.Acts.FindPath,
		C3.Behaviors.Pathfinding.Cnds.OnPathFound,
		C3.Behaviors.Pathfinding.Acts.StartMoving,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Text.Acts.SetPosToObject,
		C3.Behaviors.EightDir.Acts.SetIgnoreInput,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.System.Cnds.Else
	];
};
self.C3_JsPropNameTable = [
	{Health: 0},
	{"8Direction": 0},
	{ScrollTo: 0},
	{BoundTo: 0},
	{LineOfSight: 0},
	{Player: 0},
	{Bullet: 0},
	{DestroyOutside: 0},
	{EnemyHealth: 0},
	{Timer: 0},
	{Pathfinding: 0},
	{Enemy1: 0},
	{Sprite: 0},
	{Mouse: 0},
	{EnemyBullet: 0},
	{Sprite3: 0},
	{Solid: 0},
	{ShadowCaster: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{ShadowLight: 0},
	{Sprite7: 0},
	{Sprite2: 0},
	{Sprite6: 0},
	{LoseText: 0},
	{WinText: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Text: 0},
	{Sprite10: 0},
	{Sprite11: 0},
	{Touch: 0},
	{Enemy2: 0},
	{Bullet2: 0},
	{EnemyBullet2: 0},
	{Player2: 0}
];

self.InstanceType = {
	Player: class extends self.ISpriteInstance {},
	Bullet: class extends self.ISpriteInstance {},
	Enemy1: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	EnemyBullet: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	ShadowLight: class extends self.IShadowLightInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	LoseText: class extends self.ITextInstance {},
	WinText: class extends self.ITextInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Enemy2: class extends self.ISpriteInstance {},
	Bullet2: class extends self.ISpriteInstance {},
	EnemyBullet2: class extends self.ISpriteInstance {},
	Player2: class extends self.ISpriteInstance {}
}